FROM node:18-alpine AS deps
WORKDIR /app
COPY apps/mobile/package*.json ./
RUN npm install

FROM node:18-alpine
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY apps/mobile ./
EXPOSE 8081
CMD ["npm", "start"]
